### ISSUE TITLE
Ins't possible migrate the new Hikvision Doorbell add-on from HA to Homebridge?

### ISSUE THREAD

**Issue by VCTGomes** [judge/homebridge-hikconnect#20]
At February 9th, HomeAssistant developers seems to discovered a lot of new possibilities to integrate Hikvision doorbells to HomeAssistant. Isn't it possible to migrate to HomeBridge like HikConnect too? Or at least detect when a button was pressed to trigger a webhook from Scrypted to make the doorbell rings?

https://community.home-assistant.io/t/hikvision-doorbell-videointercom-integration/532796

Tks and good job, HikConnect has saved my live!

**Comment by judge** [comment]
Hello!
That integration works if you have local access to your outdoor station. If you have that I would not recommend to use this plugin, this is intended for people who does not have access, for example they live in a block where these devices are managed by someone else.
This plugin uses some unofficial APIs based on the Hikconnect mobile apps and it has limited feature set.
For the button press: there is no "push event" when someone pushes the button so the plugin won't know unless it would peridocially fetches this information from the door. But that would be a lot of unneccessary traffic and there would be also a delay, even is the plugin would fetch this every 5 secs. So unless someone figures out how to listen to this event this won't be available because "polling" is not the solution I would implement. :(

**Comment by VCTGomes** [comment]
Oh. I got it. I didn’t know it would this way. 

Thanks for the answer!
